import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <Head>
      <title>Create Next App</title>
      <meta content='Generated by create next app' name='description' />
      <link href='/favicon.ico' rel='icon' />
    </Head>
  );
};

export default Home;
